# Generated by Django 5.1.15 on 2026-07-24 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('color', models.CharField(default='#999999', max_length=7)),
            ],
            options={
                'db_table': 'budget_category',
            },
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rbc_transaction_id', models.CharField(max_length=120, unique=True)),
                ('posted_date', models.DateField(db_index=True)),
                ('description_raw', models.TextField()),
                ('description_normalized', models.CharField(db_index=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorization_status', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.categorymodel')),
            ],
            options={
                'db_table': 'budget_transaction',
                'ordering': ['-posted_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryRuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('times_confirmed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='budget.categorymodel')),
            ],
            options={
                'db_table': 'budget_category_rule',
                'indexes': [models.Index(fields=['match_key'], name='budget_cate_match_k_a7e22e_idx')],
            },
        ),
    ]
