import { NodeCategory } from './node.model';

export const SERVICE_CATALOG: Record<NodeCategory, string[]> = {
  Compute: ['ApplicationServer', 'Worker', 'Function', 'Container', 'VirtualMachine', 'Scheduler'],
  Networking: ['LoadBalancer', 'ApiGateway', 'Cdn', 'Dns', 'Firewall', 'Vpn', 'ServiceMesh', 'ReverseProxy'],
  Data: ['RelationalDb', 'DocumentDb', 'KeyValueStore', 'GraphDb', 'DataWarehouse', 'SearchEngine', 'TimeSeriesDb'],
  Caching: ['Cache', 'SessionStore'],
  Messaging: ['MessageQueue', 'EventBus', 'PubSub', 'StreamProcessor', 'JobBroker'],
  Storage: ['ObjectStorage', 'BlockStorage', 'FileStorage'],
  Security: ['IdentityProvider', 'SecretManager', 'CertificateManager', 'Waf'],
  Observability: ['Logging', 'Monitoring', 'Tracing', 'Alerting'],
  Group: ['NetworkBoundary', 'AvailabilityZone', 'Region', 'ServiceCluster', 'Custom'],
};

export const PROVIDER_SERVICE_NAMES: Record<string, Record<string, string>> = {
  'Compute::ApplicationServer': { Aws: 'Elastic Beanstalk', Gcp: 'App Engine', Azure: 'App Service' },
  'Compute::Worker': { Aws: 'ECS Service', Gcp: 'Cloud Run Jobs', Azure: 'Container Instances' },
  'Compute::Function': { Aws: 'Lambda', Gcp: 'Cloud Functions', Azure: 'Azure Functions' },
  'Compute::Container': { Aws: 'ECS/Fargate', Gcp: 'Cloud Run', Azure: 'Container Apps' },
  'Compute::VirtualMachine': { Aws: 'EC2', Gcp: 'Compute Engine', Azure: 'Virtual Machines' },
  'Compute::Scheduler': { Aws: 'EventBridge Scheduler', Gcp: 'Cloud Scheduler', Azure: 'Logic Apps' },
  'Networking::LoadBalancer': { Aws: 'ALB', Gcp: 'Cloud Load Balancing', Azure: 'Azure Load Balancer' },
  'Networking::ApiGateway': { Aws: 'API Gateway', Gcp: 'API Gateway', Azure: 'API Management' },
  'Networking::Cdn': { Aws: 'CloudFront', Gcp: 'Cloud CDN', Azure: 'Azure CDN' },
  'Networking::Dns': { Aws: 'Route 53', Gcp: 'Cloud DNS', Azure: 'Azure DNS' },
  'Networking::Firewall': { Aws: 'Network Firewall', Gcp: 'Cloud Firewall', Azure: 'Azure Firewall' },
  'Networking::Vpn': { Aws: 'VPN Gateway', Gcp: 'Cloud VPN', Azure: 'VPN Gateway' },
  'Networking::ServiceMesh': { Aws: 'App Mesh', Gcp: 'Traffic Director', Azure: 'Open Service Mesh' },
  'Networking::ReverseProxy': { Aws: 'ALB', Gcp: 'Cloud Load Balancing', Azure: 'Application Gateway' },
  'Data::RelationalDb': { Aws: 'RDS', Gcp: 'Cloud SQL', Azure: 'Azure SQL Database' },
  'Data::DocumentDb': { Aws: 'DynamoDB', Gcp: 'Firestore', Azure: 'Cosmos DB' },
  'Data::KeyValueStore': { Aws: 'DynamoDB', Gcp: 'Memorystore', Azure: 'Azure Cache for Redis' },
  'Data::GraphDb': { Aws: 'Neptune', Gcp: 'JanusGraph on GCE', Azure: 'Cosmos DB (Gremlin)' },
  'Data::DataWarehouse': { Aws: 'Redshift', Gcp: 'BigQuery', Azure: 'Synapse Analytics' },
  'Data::SearchEngine': { Aws: 'OpenSearch', Gcp: 'Elastic Cloud', Azure: 'Azure AI Search' },
  'Data::TimeSeriesDb': { Aws: 'Timestream', Gcp: 'Bigtable', Azure: 'Azure Data Explorer' },
  'Caching::Cache': { Aws: 'ElastiCache', Gcp: 'Memorystore', Azure: 'Azure Cache for Redis' },
  'Caching::SessionStore': { Aws: 'ElastiCache Redis', Gcp: 'Memorystore Redis', Azure: 'Azure Cache for Redis' },
  'Messaging::MessageQueue': { Aws: 'SQS', Gcp: 'Cloud Tasks', Azure: 'Azure Queue Storage' },
  'Messaging::EventBus': { Aws: 'EventBridge', Gcp: 'Eventarc', Azure: 'Event Grid' },
  'Messaging::PubSub': { Aws: 'SNS', Gcp: 'Pub/Sub', Azure: 'Service Bus Topics' },
  'Messaging::StreamProcessor': { Aws: 'Kinesis', Gcp: 'Dataflow', Azure: 'Stream Analytics' },
  'Messaging::JobBroker': { Aws: 'Step Functions', Gcp: 'Cloud Workflows', Azure: 'Durable Functions' },
  'Storage::ObjectStorage': { Aws: 'S3', Gcp: 'Cloud Storage', Azure: 'Blob Storage' },
  'Storage::BlockStorage': { Aws: 'EBS', Gcp: 'Persistent Disk', Azure: 'Managed Disks' },
  'Storage::FileStorage': { Aws: 'EFS', Gcp: 'Filestore', Azure: 'Azure Files' },
  'Security::IdentityProvider': { Aws: 'Cognito', Gcp: 'Identity Platform', Azure: 'Azure AD B2C' },
  'Security::SecretManager': { Aws: 'Secrets Manager', Gcp: 'Secret Manager', Azure: 'Key Vault' },
  'Security::CertificateManager': { Aws: 'ACM', Gcp: 'Certificate Manager', Azure: 'App Service Certificates' },
  'Security::Waf': { Aws: 'WAF', Gcp: 'Cloud Armor', Azure: 'Azure WAF' },
  'Observability::Logging': { Aws: 'CloudWatch Logs', Gcp: 'Cloud Logging', Azure: 'Azure Monitor Logs' },
  'Observability::Monitoring': { Aws: 'CloudWatch', Gcp: 'Cloud Monitoring', Azure: 'Azure Monitor' },
  'Observability::Tracing': { Aws: 'X-Ray', Gcp: 'Cloud Trace', Azure: 'Application Insights' },
  'Observability::Alerting': { Aws: 'CloudWatch Alarms', Gcp: 'Cloud Alerting', Azure: 'Azure Monitor Alerts' },
};

export const CATEGORY_COLORS: Record<NodeCategory, string> = {
  Compute: '#89b4fa',
  Networking: '#a6e3a1',
  Data: '#cba6f7',
  Caching: '#fab387',
  Messaging: '#f9e2af',
  Storage: '#94e2d5',
  Security: '#f38ba8',
  Observability: '#89dceb',
  Group: '#6c7086',
};
