pub mod create_diagram;
pub mod delete_diagram;
pub mod fix_diagram;
pub mod generate_diagram;
pub mod get_diagram;
pub mod list_diagrams;
pub mod modify_diagram;
pub mod update_diagram;
pub mod validate_diagram;
