from abc import ABC, abstractmethod

from budget.budget.domain.entities import Transaction


class TransactionRepository(ABC):
    @abstractmethod
    def save(self, tx: Transaction) -> Transaction: ...
    @abstractmethod
    def get(self, tx_id: int) -> Transaction: ...
    @abstractmethod
    def list_pending(self) -> list[Transaction]: ...
    @abstractmethod
    def list_for_month(self, year: int, month: int) -> list[Transaction]: ...
    @abstractmethod
    def update_category(self, tx_id: int, category_id: int, status: str) -> Transaction: ...
    @abstractmethod
    def exists(self, rbc_transaction_id: str) -> bool: ...